# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapsheetdownload.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapsheetDownload(object):
    def setupUi(self, MapsheetDownload):
        MapsheetDownload.setObjectName(_fromUtf8("MapsheetDownload"))
        MapsheetDownload.resize(649, 389)
        self.verticalLayout_5 = QtGui.QVBoxLayout(MapsheetDownload)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_50k = QtGui.QLabel(MapsheetDownload)
        self.label_50k.setObjectName(_fromUtf8("label_50k"))
        self.horizontalLayout.addWidget(self.label_50k)
        self.fromExtent50k = QtGui.QPushButton(MapsheetDownload)
        self.fromExtent50k.setObjectName(_fromUtf8("fromExtent50k"))
        self.horizontalLayout.addWidget(self.fromExtent50k)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.input50k = QtGui.QLineEdit(MapsheetDownload)
        self.input50k.setObjectName(_fromUtf8("input50k"))
        self.verticalLayout_3.addWidget(self.input50k)
        self.group_50k = QtGui.QGroupBox(MapsheetDownload)
        self.group_50k.setObjectName(_fromUtf8("group_50k"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.group_50k)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.downloadCanVec = QtGui.QCheckBox(self.group_50k)
        self.downloadCanVec.setToolTip(_fromUtf8(""))
        self.downloadCanVec.setChecked(False)
        self.downloadCanVec.setObjectName(_fromUtf8("downloadCanVec"))
        self.verticalLayout.addWidget(self.downloadCanVec)
        self.downloadNTDB50k = QtGui.QCheckBox(self.group_50k)
        self.downloadNTDB50k.setObjectName(_fromUtf8("downloadNTDB50k"))
        self.verticalLayout.addWidget(self.downloadNTDB50k)
        self.downloadDEM50k = QtGui.QCheckBox(self.group_50k)
        self.downloadDEM50k.setObjectName(_fromUtf8("downloadDEM50k"))
        self.verticalLayout.addWidget(self.downloadDEM50k)
        self.downloadTopo50k = QtGui.QCheckBox(self.group_50k)
        self.downloadTopo50k.setObjectName(_fromUtf8("downloadTopo50k"))
        self.verticalLayout.addWidget(self.downloadTopo50k)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(89, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.group_50k)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_250k = QtGui.QLabel(MapsheetDownload)
        self.label_250k.setObjectName(_fromUtf8("label_250k"))
        self.horizontalLayout_2.addWidget(self.label_250k)
        self.fromExtent250k = QtGui.QPushButton(MapsheetDownload)
        self.fromExtent250k.setObjectName(_fromUtf8("fromExtent250k"))
        self.horizontalLayout_2.addWidget(self.fromExtent250k)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.input250k = QtGui.QLineEdit(MapsheetDownload)
        self.input250k.setObjectName(_fromUtf8("input250k"))
        self.verticalLayout_4.addWidget(self.input250k)
        self.group_250k = QtGui.QGroupBox(MapsheetDownload)
        self.group_250k.setObjectName(_fromUtf8("group_250k"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.group_250k)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.downloadCanVec_plus = QtGui.QCheckBox(self.group_250k)
        self.downloadCanVec_plus.setObjectName(_fromUtf8("downloadCanVec_plus"))
        self.verticalLayout_2.addWidget(self.downloadCanVec_plus)
        self.downloadNTDB250k = QtGui.QCheckBox(self.group_250k)
        self.downloadNTDB250k.setObjectName(_fromUtf8("downloadNTDB250k"))
        self.verticalLayout_2.addWidget(self.downloadNTDB250k)
        self.downloadDEM250k = QtGui.QCheckBox(self.group_250k)
        self.downloadDEM250k.setObjectName(_fromUtf8("downloadDEM250k"))
        self.verticalLayout_2.addWidget(self.downloadDEM250k)
        self.downloadTopo250k = QtGui.QCheckBox(self.group_250k)
        self.downloadTopo250k.setObjectName(_fromUtf8("downloadTopo250k"))
        self.verticalLayout_2.addWidget(self.downloadTopo250k)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.group_250k)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.outputDir = QtGui.QLineEdit(MapsheetDownload)
        self.outputDir.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.outputDir.setObjectName(_fromUtf8("outputDir"))
        self.horizontalLayout_6.addWidget(self.outputDir)
        self.browserButton = QtGui.QPushButton(MapsheetDownload)
        self.browserButton.setObjectName(_fromUtf8("browserButton"))
        self.horizontalLayout_6.addWidget(self.browserButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.addMapLayers = QtGui.QCheckBox(MapsheetDownload)
        self.addMapLayers.setChecked(True)
        self.addMapLayers.setObjectName(_fromUtf8("addMapLayers"))
        self.horizontalLayout_8.addWidget(self.addMapLayers)
        self.progressBar = QtGui.QProgressBar(MapsheetDownload)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_8.addWidget(self.progressBar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.status = QtGui.QPlainTextEdit(MapsheetDownload)
        self.status.setObjectName(_fromUtf8("status"))
        self.horizontalLayout_7.addWidget(self.status)
        self.buttonBox = QtGui.QDialogButtonBox(MapsheetDownload)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)

        self.retranslateUi(MapsheetDownload)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MapsheetDownload.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MapsheetDownload.reject)
        QtCore.QMetaObject.connectSlotsByName(MapsheetDownload)

    def retranslateUi(self, MapsheetDownload):
        MapsheetDownload.setWindowTitle(_translate("MapsheetDownload", "NTS Data Download", None))
        self.label_50k.setText(_translate("MapsheetDownload", "50k Mapsheets to Download", None))
        self.fromExtent50k.setText(_translate("MapsheetDownload", "From Extent", None))
        self.input50k.setToolTip(_translate("MapsheetDownload", "<html><head/><body><p>Separate multiple 50k NTS mapsheets with a comma.</p><p>Each mapsheet must be 6 characters long.</p><p>Example: <span style=\" font-weight:600;\">092h12,092I10</span></p></body></html>", None))
        self.input50k.setPlaceholderText(_translate("MapsheetDownload", "Example: 092h12, 092I10", None))
        self.group_50k.setTitle(_translate("MapsheetDownload", "1:50000 NTS Datasets to Download", None))
        self.downloadCanVec.setText(_translate("MapsheetDownload", "CanVec Vector Data", None))
        self.downloadNTDB50k.setText(_translate("MapsheetDownload", "NTDB Vector Data", None))
        self.downloadDEM50k.setText(_translate("MapsheetDownload", "DEM Raster Data", None))
        self.downloadTopo50k.setText(_translate("MapsheetDownload", "Topographic Raster Maps", None))
        self.label_250k.setText(_translate("MapsheetDownload", "250k Mapsheets to Download", None))
        self.fromExtent250k.setText(_translate("MapsheetDownload", "From Extent", None))
        self.input250k.setToolTip(_translate("MapsheetDownload", "<html><head/><body><p>Separate multiple 250k NTS mapsheets with a comma.</p><p>Each mapsheet must be 4 characters long.</p><p>Example: <span style=\" font-weight:600;\">092H,092i</span></p></body></html>", None))
        self.input250k.setPlaceholderText(_translate("MapsheetDownload", "Example: 092H,092i", None))
        self.group_250k.setTitle(_translate("MapsheetDownload", "1:250000 NTS Datasets to Download", None))
        self.downloadCanVec_plus.setText(_translate("MapsheetDownload", "CanVec+ Vector Data", None))
        self.downloadNTDB250k.setText(_translate("MapsheetDownload", "NTDB Vector Data", None))
        self.downloadDEM250k.setText(_translate("MapsheetDownload", "DEM Raster Data", None))
        self.downloadTopo250k.setText(_translate("MapsheetDownload", "Topographic Raster Maps", None))
        self.outputDir.setPlaceholderText(_translate("MapsheetDownload", "Directory where data will be saved", None))
        self.browserButton.setText(_translate("MapsheetDownload", "Browse", None))
        self.addMapLayers.setText(_translate("MapsheetDownload", "Add downloaded files into the layer tree", None))

